### ISSUE TITLE
gpl 2

### ISSUE THREAD

**Issue by aoloe** [nitramr/scribus-indigo#1]
scribus is distributed under the gpl 2 license... i don't think that the team will be willing to integrate code under the gpl 3... since this would mean upgrading the license...

(as far as i understand it, the license says that you can redistribute scribus unter gpl 2 or later, but if they include code with gpl 3, the license has to be changed as gpl 3 or later... but i might be mistaking).

you should probably discuss this with somebody from the team.

**Comment by nitramr** [comment]
My mistake, license file has been removed from branch.

**Comment by nitramr** [comment]
I have changed the license of the included IndigoDock files to GPL 2.
