### ISSUE TITLE
Is there a reason why you aren't using the latest Qt Creator 4.1.0 ?

### ISSUE THREAD

**Issue by luzpaz** [nitramr/scribus-indigo#14]
I saw in the last commit that you're using Qt Creator 3.6.1
https://github.com/nitramr/scribus-indigo/commit/4f0e6ad68e1de4aac2ca3dc507dc87e0d1e05e2c#diff-780546f5e957f70a5e8165859dfbb404R3

**Comment by luzpaz** [comment]
@nitramr  I understand that Qt Designer has been improved in Qt4.1.0

**Comment by nitramr** [comment]
The only reason is I have not updated to Qt 5.7. Now, my system is up to date. Thanks for the hint.

**Comment by luzpaz** [comment]
:+1:
