### ISSUE TITLE
add some info to about.cpp

### ISSUE THREAD

**Issue by gregp-scribus** [nitramr/scribus-indigo#15]
I think it would be good for you to edit about.cpp so you identify this as a github work in progress, and update the date when you see fit.

**Comment by gregp-scribus** [comment]
Here is something I tried, which is easy
Change Line 122 in about.cpp to
    QString BUILD_NAME = "Scribus Indigo Dock";
What you see then in the About - Scribus dialog:
Scribus Version 1.5.3svn "Scribus Indigo Dock"

Lines 117 and 118 could also perhaps reflect some particular pertinent date:
    QString BUILD_DAY = "18";
    QString BUILD_MONTH = CommonStrings::september;

**Comment by luzpaz** [comment]
Exactly, check https://github.com/scribusproject/scribus/commit/00295c2b494d5ed7926145065fdfb6b823491679

**Comment by nitramr** [comment]
Done
