### ISSUE TITLE
rogue horizontal lines appear across canvas

### ISSUE THREAD

**Issue by luzpaz** [nitramr/scribus-indigo#16]
Manjaro 16.10 ~Qt 5.7~ Build  https://github.com/nitramr/scribus-indigo/commit/571247bb26225c218e9ef55b8ab5181f248e4261 (using the appimage to test)
1. open and place a sidebar menu like action-history  
2. open new document
Result: see lines  
3. close document 
Result: see remnants of the lines 

See gif
![indigo](https://cloud.githubusercontent.com/assets/4140247/20230838/0973263c-a82c-11e6-9c3a-d2439eff0313.gif)

**Comment by luzpaz** [comment]
Can anyone reproduce this issue?
CC @gregp-scribus

**Comment by nitramr** [comment]
Not on Ubunut 16.04. I have removed the ".scribus" folder in home folder at first to get a "fresh" system.

**Comment by gregp-scribus** [comment]
I'm not seeing this on fedora 24.

**Comment by nitramr** [comment]
@luzpaz is it still reproduceable on your system with the latest appimage?

**Comment by luzpaz** [comment]
will check later today :)

**Comment by luzpaz** [comment]
I still see them (not exactly the same as before) when I invoke with 
`QT_SCALE_FACTOR=0.786 ./scribus-git4b9541e-glibc2.14-x86-64.appimage`
But if i just invoke the appimage by itself I don't see them. So I think you can close this issue.
