### ISSUE TITLE
can't get appimage to work

### ISSUE THREAD

**Issue by gregp-scribus** [nitramr/scribus-indigo#19]
I get these messages on Fedora 24:

Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
ImportError: No module named site
Scribus Crash
-------------
Scribus crashes due to Signal #11
Segmentation fault (core dumped)

**Comment by nitramr** [comment]
I have to find a way to add python libs to the appimage.

**Comment by luzpaz** [comment]
@probonop please advise

**Comment by luzpaz** [comment]
err i meant @probonopd

**Comment by gregp-scribus** [comment]
is there anything I can add to the command?
why can't it use my python libs?

**Comment by probonopd** [comment]
Which version of Python is installed on your system?

**Comment by gregp-scribus** [comment]
python-2.7.12

**Comment by probonopd** [comment]
That is strange. I assume that Python is working outside of the AppImage?

**Comment by gregp-scribus** [comment]
Of course. Maybe it has something to do with setting system variables?

**Comment by probonopd** [comment]
Possibly. Although we are only prepending to `$PYTHONPATH` which normally should not hurt if I am not wrong.

**Comment by gregp-scribus** [comment]
Maybe I'm getting somewhere.
In the konsole, I typed "export PYTHONHOME=/usr/lib/python2.7" then ran the appimage again.

Now the only warning before crash is "No module named site"
??

**Comment by gregp-scribus** [comment]
Can't seem to get around this No module named site.
Ideas from googling are not helping.
I can find a "site.py" in /usr/lib64/python2.7/, but not in /usr/lib/python2.7/.
Perhaps that's the reason, but seems insurmountable.

**Comment by gregp-scribus** [comment]
TA-DAAAAA!
Here is what I needed to do in command line:
export PYTHONPATH=/usr/lib64/python2.7

**Comment by probonopd** [comment]
Ah, interesting! Is PYTHONPATH set to something by default in your distribution?

**Comment by gregp-scribus** [comment]
Must be set to something wrong, but it didn't seem to be set to anything.
When I entered $PYTHONPATH in the commandline, got nothing.
As I check this out, it seems that PYTHONPATH is where the system looks for extra modules. It looks like, at least in fedora 24, /usr/lib/python2.7 has a different structure from /usr/lib64/python2.7. In the former, /usr/lib/python2.7 has no modules, only the directory site-packages, in the latter, there a lot of modules in /usr/lib64/python2.7 (is the appimage 32-bit? Maybe that's the issue.)
BTW, I tried creating a symbolic link to site.py, but then it complained it couldn't find the module os)...

So now I've edited my .bashrc file to make it stick.

**Comment by probonopd** [comment]
Would still be nice to find a solution that solves this inside the AppImage. One solution would be to bundle Python and its standard library inside the AppImage, thus becoming entirely independent from the system Python. This type of issue comes from the fact that every distribution insists on naming stuff slightly differently and putting stuff into slightly different places. One reason more why I like _upstream packaging_, where I can consume software exactly in the way the original authors intended.

**Comment by gregp-scribus** [comment]
A side effect seems to be that if I run this appimage, then my "regular" Scribus builds can't find python.
I think I'll just stay with the building my own method.

**Comment by gregp-scribus** [comment]
using the latest appimage from Nov 16, everything seems to work Ok now. There was a problem with icons not being found, and this is fixed now too.
The Scribus Light theme doesn't work for me, since the icons are almost impossible to see against the background. Dark and Darker work Ok.

**Comment by nitramr** [comment]
Did you switch the icon set to dark as you use the light theme? You can set themes and icons independent. Default is dark theme and light icons.

**Comment by luzpaz** [comment]
can we close this issue guys ?

**Comment by nitramr** [comment]
Yes, we can.

**Comment by corebots** [comment]
hello, i just got the same error on Fedora 26, the above mentioned command helped and solved it, thanks :)
