### ISSUE TITLE
Activate travisci for this repo

### ISSUE THREAD

**Issue by luzpaz** [nitramr/scribus-indigo#2]
@nitramr this is awesome. Lets get TravisCI started for this: check out https://docs.travis-ci.com/user/getting-started/#To-get-started-with-Travis-CI%3A

It's simple and steps 3 and 4 are already done.

**Comment by luzpaz** [comment]
@nitramr just sign up for travisci and I'll take care of the rest. Then we can use it to see errors/warnings whenever new code is merged or proposed via Pull Request

**Comment by nitramr** [comment]
Hi Luzpaz, thanks for helping out. Step 1 and 2 are done.

**Comment by luzpaz** [comment]
awesome. So quick question:
can you pull in the latest changes from scribus trunk and maintain the work you've already done ?
I ask because of 2 commits:
https://github.com/scribusproject/scribus/commit/fafe5f5b115420f1dcac3a28eb3de57c36feaf8a
&
https://github.com/scribusproject/scribus/commit/57a4f7257060692e31ae3f51944d99cdd6cc3c22

**Comment by luzpaz** [comment]
I altered the badge to reflect the build of this repo in PR https://github.com/nitramr/scribus-indigo/pull/3

**Comment by nitramr** [comment]
I have copied the current scribus code base from today and merged my changes to it. My local compiling was succesfully.
