### ISSUE TITLE
sidebar menu names are truncated 

### ISSUE THREAD

**Issue by luzpaz** [nitramr/scribus-indigo#23]
"Align and Distrib" and "Action Histo"
See gif
![sidebar-menu-names-truncated](https://cloud.githubusercontent.com/assets/4140247/20282306/35ce614e-aa82-11e6-89ea-6e3e3e5e6489.png)

Manjaro 16.10   
scribus-indigo https://github.com/nitramr/scribus-indigo/commit/43554ee171eff90ffc93060aa3ef854ab60fbd01

**Comment by nitramr** [comment]
I see, the text in panel header will paint in eventPaint() function. Maybe there is a wrong calculation of font width. I will check it.

Is it a pixel perfect screenshot or do you use a retina display? I see that all control elements are totally wrong scaled.

**Comment by luzpaz** [comment]
yea.. i'm not on retina... but I am on a HiDPI laptop and i need to scale Qt artifically 
so that may be an issue
Here is how I invoke the binary:
`[user@beast Downloads]$ QT_SCALE_FACTOR=0.786 ./scribus-git43554ee-glibc2.14-x86-64.appimage`

**Comment by nitramr** [comment]
Ok, font width should be fixed. Label width will calculate of available space and not on text width and I made the font size dynamic based on the settings in preferences.

Let's wait when Travis CI is done.

**Comment by nitramr** [comment]
Please, try out. https://transfer.sh/5tjbi/scribus-git4b9541e-glibc2.14-x86-64.appimage

**Comment by luzpaz** [comment]
Thanks Martin!
You fixed it in https://github.com/nitramr/scribus-indigo/commit/4b9541eb3c24bc1ba4c1e8f34f8af2cb58b45d56
