### ISSUE TITLE
wiki typo

### ISSUE THREAD

**Issue by luzpaz** [nitramr/scribus-indigo#24]
> The Indigo branch is an inofficial experimental   

Unofficial

**Comment by luzpaz** [comment]
> The initial idea was born in early 2015 in Scribus forums where some Scribus users....  

Possibilities:

> in **a** Scribus **UI sub-forum**

or 

> in **the** Scribus forums

or 

> in a Scribus **forum thread**

**Comment by nitramr** [comment]
thanks, fixed.
