### ISSUE TITLE
Themes must retain platform styling

### ISSUE THREAD

**Issue by MrB74** [nitramr/scribus-indigo#25]
Hi Tim

With your changes to the theme selector, the GUI is now missing the Mac style. We need to keep the ability to let people use the pure platform styles somehow. Therefore, we also need theming to work, eg in Mac style applied to the new dock and palettes. I'm also open to a pure "indigo style", akin to Qt Creator's own style.

thanks
Craig

**Comment by nitramr** [comment]
Hi Craig,

I brought back the system themes. Default is "Scribus Dark" theme, but in perferences you can switch to native styles which are supported by your system.

All non system themes will automatic based on Fusion-Style + additional QSS Styles, like my new themes.
Fusion is most styling freindly. If someone wants customize the native styles it is possible via "stylesheet.css" in application folder.

Changes in:
7a91d9e4fbe9de015caaad16ca5970176afd63c3

**Comment by luzpaz** [comment]
> If someone wants customize the native styles it is possible via "stylesheet.css" in application folder.

This is very exciting. I think people will appreciate this. Especially if we make it easy for them to add their own icons. Very cool @nitramr

**Comment by nitramr** [comment]
@luzpaz for the custom theme files I have modified the logic which loads images from css file. You can put any image which you want from current icon set in to the css files. The system generates an absolute path based on selected iconset.

I can rollout this logic for the default stylesheet.css too.  :)
