### ISSUE TITLE
Program hangs when opening script dialog without open document

### ISSUE THREAD

**Issue by stefanhusmann** [nitramr/scribus-indigo#27]
Start scribus, click "Scripter" without opening a document. You will get an error message "You need a Document open", which cannot be closed. You have to kill scribus forcefully.

**Comment by luzpaz** [comment]
I can reproduce this on scribus-svn (Latest HEAD). Will open a bug report on bugs.scribus.net. Thanks @stefanhusmann

**Comment by nitramr** [comment]
I can confirm it. But it is only for the script, "autoquote". All others have a ok button to close the dialog.

I have filed a bug, because it is in Scribus nightly built too.
https://bugs.scribus.net/view.php?id=14376

**Comment by luzpaz** [comment]
@nitramr haha.. nice :+1:  I'll confirm your bug

**Comment by luzpaz** [comment]
jean offered a fix in [r21521](https://www.scribus.net/websvn/comp.php?repname=Scribus&compare[]=/@21520&compare[]=/@21521)

**Comment by nitramr** [comment]
fix applied too.
