### ISSUE TITLE
OSX TravisCI build fails because it exceeds compilation time

### ISSUE THREAD

**Issue by luzpaz** [nitramr/scribus-indigo#29]
https://github.com/nitramr/scribus-indigo/issues/17#issuecomment-261154103
Still not sure how to fix this...

**Comment by nitramr** [comment]
there was a bug in OSX #ifdev, while compiling on Ubuntu I couldn't see it. Without a local compling on a mac it is like try and error. :(

**Comment by luzpaz** [comment]
yea..i'll ask @MrB74 since he is on OSX. I don't have my macbook pro to test on anymore. 
BTW, https://github.com/scribusproject/scribus/commit/91906e0be233053b61a0d58937eb8e2c962ad881 was just committed to fix a hunspell issue

**Comment by nitramr** [comment]
The reason why is I replaced a lot of icons which uses a QPixmap with QIcon, because the new themes need a disabled state for icons and the best way was to store this state in an QIcon.

I'll add the the hunspell fix.

**Comment by nitramr** [comment]
Travis CI has finished compiling for OSX
