### ISSUE TITLE
Make ~/.config/scribus-indigo/ the default prefs dir

### ISSUE THREAD

**Issue by luzpaz** [nitramr/scribus-indigo#31]
Since SVN recently follows XDG standards...the new place for the Scribus preference files are in ~/.config/scribus instead of ~/.scribus
Invoking indigo-scribus with no flags will use the default scribus prefs and we don't want that. So ways around that, we can use some flags mentioned in https://wiki.scribus.net/canvas/CMake_Build_Options#1.5.x.svn.2B
like:
```APPLICATION_CONFIG_DIR : PATH  : specify the user configuration directory at compile time```
for example:  
```cmake -DAPPLICATION_CONFIG_DIR=~/.config/scribus-indigo```

We can mention this also in the README so people can test appropriately. Also they'll need to invoke scribus-indigo with a special flag:
```scribus-indigo --prefs ~/.config/scribus-indigo```

**Comment by luzpaz** [comment]
ref. https://github.com/nitramr/scribus-indigo/issues/13#issuecomment-262107820

**Comment by luzpaz** [comment]
maybe you should hardcode it and if someone wants to specify a different config dir they can via the CLI when the run scribus-indigo ?

**Comment by nitramr** [comment]
done in https://github.com/nitramr/scribus-indigo/commit/7239a8eb27c5f47bd33592949efaa6490facb884
