### ISSUE TITLE
Workspace loader can't handle missing entries in prefs file

### ISSUE THREAD

**Issue by nitramr** [nitramr/scribus-indigo#34]
if an existing panel is missing in prefs it will add in an own floating window frame instead of additional to any dock.

IndigoDockManager.cpp line 499

**Comment by nitramr** [comment]
fixed!

Workspace loader will add panel leftovers if they are not already sorted. This fixes also broken workspace files or handle new panels.

**Comment by luzpaz** [comment]
@nitramr fixed #34 in c5d132e79c17890369a18b4a83e40ab7504b194b
