### ISSUE TITLE
Per the scribus-indigo wiki style guide philosophy: uniformity of the delete button

### ISSUE THREAD

**Issue by luzpaz** [nitramr/scribus-indigo#38]
Hey @nitramr 
I was reading your style guide and remembered a ticket that @aoloe opened sometime ago: https://bugs.scribus.net/view.php?id=10162 "Find a common icon for the delete buttons"
I'm mentioning it here as a reference going forward.

**Comment by nitramr** [comment]
Cool, I have some ideas how we can unify it. A made a comment in the issue.
