### ISSUE TITLE
doesn't compile on poppler 0.60

### ISSUE THREAD

**Issue by l00kanio** [nitramr/scribus-indigo#47]
When I try to compile Scirbus-Indigo (from Arch's aur), build dies on building importpdf plugin with:

make[2]: *** [scribus/plugins/import/pdf/CMakeFiles/importpdf.dir/build.make:78: scribus/plugins/import/pdf/CMakeFiles/importpdf.dir/importpdf.cpp.o] Error 1                                                       
make[1]: *** [CMakeFiles/Makefile2:1810: scribus/plugins/import/pdf/CMakeFiles/importpdf.dir/all] Error 2                                                                                                           
make: *** [Makefile:152: all] Error 2  

It is known issue with Scribus. Patch has been already added to upstream AFAIK. Is there any chance it could be solved in Scribus Indigo as well?

**Comment by nitramr** [comment]
Hi l00kanio, next time when I'm merge the original Scribus base with the Indigo branch it should be fixed. Currently I'm focusing on another project for polishing the UI. Could be take a while until I have time to update the indigo branch.

Pull requests are welcome too. ;)

**Comment by l00kanio** [comment]
Thank you for positive feedback. So I keep fingers crossed for your work :-)
